name: face-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.22.2
  - opencv=4.5.5
  - pandas=1.4.0
  - pcre=8.45
  - pip=22.0.3
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - dlib=19.22.0
  - urllib3=1.26.8
# prefix: /home/jaeo/anaconda3/envs/face-test
